### ISSUE TITLE
绑定用户问题

### ISSUE THREAD

**Issue by a632079** [NodeBB-China/nodebb-plugin-sso-qq-fix#2]
版本 0.4.9 存在用户绑定问题(估计是uid问题).
描述:你已经登录。使用绑定，却帮你新建了一个用户。
 
----

可能存在的问题：解绑。
这些问题将在这个issue统一处理。
最慢下周5解决

**Comment by a632079** [comment]
@julianlam I found that sso-github and sso-google are using email what comes from oauth api.However,This API can't get email address.so,I can't let this plugin use profiles to bind user.Could you tell me whether some apis is exist(e.g. if you logged in,you can get your email or uid).

**Comment by julianlam** [comment]
For QQ, I am afraid I do not know if such a scope exists. You would have to contact someone from QQ about it....

**Comment by a632079** [comment]
ok,I will try to use common hook to get user's email.
