### ISSUE TITLE
关于qq登录的bug

### ISSUE THREAD

**Issue by riddle911** [NodeBB-China/nodebb-plugin-sso-qq-fix#6]
问题描述
直接qq登录-删除账户-重新qq登录，页面一直显示“session无法匹配，您的登入状态已经失效”，web不停无限刷新。

update:
正常注册新用户，再绑定qq，一切正常。

**Comment by a632079** [comment]
预计2个双休解决吧888

**Comment by a632079** [comment]
初步查看，是删除用户的时候，可能回调异常，插件未处理

**Comment by riddle911** [comment]
在nodebb-cn.org测试。删除账号再qq登录仍显示session....blah blah

**Comment by a632079** [comment]
0 0 可能是未清除session,你尝试下Github或Google的绑定看看，如果它没问题的话，我继续修
