### ISSUE TITLE
无法获取用户qq邮箱

### ISSUE THREAD

**Issue by helloxz** [NodeBB-China/nodebb-plugin-sso-qq-fix#7]
使用qq快捷注册后，用户邮箱被随机分配的，比如这样的格式：D6E8625EDCA8F833DDC397057CB6036D@norelpy.qq.com ，导致用户无法获取验证邮件。

**Comment by a632079** [comment]
这是大多数不提供Email的SSO的通常做法。目前版本用户可行的解决方法:手动修改Email。

--------------------------------------------------------------------------------------------------------
未来，会有两种解决方案:
1.我这建个单独界面用于提供注册表单。
2.等官方完善这个钩子( https://github.com/NodeBB/NodeBB/issues/5671 )，稍后我们就会更新:D
感谢您的支持，这个issue会在问题解决后关闭 😄 😄

**Comment by a632079** [comment]
目前进度:Debug,预计明天会发布提供注册页的版本:D.
