### ISSUE TITLE
Suggest non-readonly input field for "Authorization callback URL"

### ISSUE THREAD

**Issue by jiangcaiyang** [NodeBB-China/nodebb-plugin-sso-qq-fix#8]
Because my forum runs under nginx, and modern browser like chrome and safari automatically convert http to https request, whereas "Authorization callback URL" may be the one that uses http prefix as a matter of fact. 
For instance, my default callback is:
```
http://qtdream.com:1237/auth/qq/callback
```

Which may be redirect to ```https://qtdream.com:1237/auth/qq/callback``` and result in error.

I need this field being configurable.

**Comment by a632079** [comment]
We Use `nconf.get("url")+"auth/qq/callback` as display url.
In fact, we just add a router to handle request without original url.
To Solve this problem, please edit your config.json. set url, using https instead of http.

**Comment by jiangcaiyang** [comment]
Alright, I'll do that.
